export const DATA = [
    {
        id: 0,
        name: 'Jason Smith', 
        enterprise: 'Advisor and Consultant at Stripe Inc', 
        about: 'ajfndviuebfaidvifnsdvfuibiafdvnfafuidsvfubvofuadbviubfsiafndisvufnajfnduviun asdjoifnsio dcuioanwdivj 9aeionspdvfousnfaiou dvpuavud zuipav pupauik', 
        local: 'Saint-Petersburg, Russia', 
        facebook: 'kevinsmith55',
        linkedin:'kevin_smith', 
        instagram: 'kevinSmith', 
        twitter: 'kevin_smith', 
        cea: '01/01/2020', 
        cga: '01/01/2020', 
        cpa10: '01/01/2020',
        cpa20: '01/01/2020',
        cnpi: '01/01/2020', 
        percent: 20,
        training: 'sim', 
        consultory: 'sim', 
        course: 'não', 
        feedback: 3.7,
    },{
        id: 1,
        name: 'Jack Smith', 
        enterprise: 'Advisor and Consultant Inc', 
        about: 'fdvnfafuidsvfubvofuadbviubfsiafndisvufnajfnduviun asdjoifnsio dcuioanwdivj 9aeionspdvfousnfaiou dvpuavud zuipav pupauik', 
        local: 'Caruaru, Pernanbuco', 
        facebook: 'jacksmith44',
        linkedin:'jack_smith', 
        instagram: 'jackSmith', 
        twitter: 'jack_smith', 
        cea: '03/01/2020', 
        cga: '04/01/2020', 
        cpa10: '05/01/2020',
        cpa20: '08/01/2020',
        cnpi: '10/01/2020', 
        percent: 20,
        training: 'sim', 
        consultory: 'sim', 
        course: 'não', 
        feedback: 2.5,
    }

]
